name: Docker BUILD ALL TEST

on:
  push:
    branches: [ "main" ]
    paths:
      - 'back/**'
      - 'front/**'
      - 'db/**'
  
jobs:
  build:
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: jean-baptiste-d/cloud-native-jeanbaptiste/
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            back:
              - 'back/**'
            front:
              - 'front/**'
            db:
              - 'db/**'
      -        
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USER_REGISTRY }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -         
        name: Build and push back
        if: steps.changes.outputs.back == 'true'
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}back:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}back:1.0
          context: ./back
      -         
        name: Build and push front
        if: steps.changes.outputs.front == 'true'
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}front:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}front:1.0
          context: ./front
      -         
        name: Build and push db
        if: steps.changes.outputs.db == 'true'
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}db:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}db:1.0
          context: ./db